config/routes.rb
Rails.application.routes.draw do

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
	root "welcome#show"
	get "/auth/:provider/callback" => "sessions#create_from_omniauth"


	resources :users
  get "/search" => "listings#search", as: "search"
	resources :listings do
  	resources :reservations
	end

  resources :reservations, only: [:show] do
    get 'braintree/new'
    post 'braintree/checkout'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authentication.rb
class Authentication < ApplicationRecord
  belongs_to :user

  def self.create_with_omniauth(auth_hash)
    self.new(
      provider: auth_hash["provider"],
      uid: auth_hash["uid"],
      token: auth_hash["credentials"]["token"]
    )
  end

  def update_token(auth_hash)
    self.token = auth_hash["credentials"]["token"]
    self.save
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
 	belongs_to :user
 	has_many :reservations

 	mount_uploaders :images, ImageUploader

	scope :property, -> (property) { where property: property }
	scope :country, -> (country) { where("country ILIKE ?", "%#{country}%") }
	scope :rooms, -> (rooms) { where rooms: rooms }
	
end

 

app/models/reservation.rb
class Reservation < ApplicationRecord
	 belongs_to :user
	 belongs_to :listing

	 before_save :check_overlapping_dates, :check_owner

	 def total_price
		self.listing.price * (self.end_date - self.start_date).to_i
	 end

	 private
	 def check_overlapping_dates
	 	listing = self.listing

	 	listing.reservations.each do |reservation|
	 		if self.start_date <= reservation.end_date && reservation.start_date <= self.end_date
      			return errors.add(:overlap, "This date is unavailable")
	 		end
	 	end
	 end

	 def check_owner
	 	if self.user == self.listing.user
      		errors.add(:owner, "Can't make reservation for own listing")
      	end
	 end

end

app/models/user.rb
class User < ApplicationRecord
 include Clearance::User

 has_many :authentications, dependent: :destroy
 has_many :listings

 mount_uploader :avatar, AvatarUploader

 def self.create_with_auth_and_hash(authentication, auth_hash)
   user = self.create!(
     email: auth_hash["info"]["email"],
     password: SecureRandom.hex(10)
   )
   user.authentications << authentication
   return user
 end

 # grab google to access google for user data
 def google_token
   x = self.authentications.find_by(provider: 'google_oauth2')
   return x.token unless x.nil?
 end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/braintree_controller.rb
class BraintreeController < ApplicationController
  def new
      @reservation = Reservation.find(params[:reservation_id])
      @client_token = Braintree::ClientToken.generate
  end

  def checkout

      reservation = Reservation.find(params[:reservation_id])

      nonce_from_the_client = params[:checkout_form][:payment_method_nonce]

      result = Braintree::Transaction.sale(
      :amount => reservation.total_price, #this is currently hardcoded
      :payment_method_nonce => nonce_from_the_client,
      :options => {
          :submit_for_settlement => true
        }
      )

      if result.success?
        reservation.confirmation = true
        reservation.save

        redirect_to :root, :flash => { :success => "Transaction successful!" }
      else
        redirect_to :root, :flash => { :alert => "Transaction failed. Please try again." }
      end
  end


end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

	def index
    	@listings = Listing.all
	end

	def show
    	@listing = Listing.find(params[:id])

	end

  	def new
  		@listing = Listing.new
	end

	def edit
  		@listing = Listing.find(params[:id])
	end

	def create
		@listing = Listing.new(listing_params)
 		@listing.user_id = current_user.id

  		if @listing.save
    		redirect_to @listing
  		else
    		render 'new'
  		end
	end
	  
	def update
  		@listing = Listing.find(params[:id])
 
  		if @listing.update(listing_params)
    	redirect_to @listing
  		else
    	render 'edit'
  		end
	end

	def destroy
 		 	@listing = Listing.find(params[:id])
  			@listing.destroy

  			redirect_to listings_path
	end

  def search
      @listings = Listing.all

      @listings = @listings.property(params[:property]) if params[:property].present?
      @listings = @listings.country(params[:country]) if params[:country].present?
      @listings = @listings.rooms(params[:rooms]) if params[:rooms].present?
      render "index"
  end


  private
  	def listing_params
   	 	params.require(:listing).permit(:bookings, :property, :name, :country, :rooms, :toilets, :price ,images: [])
  	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	def create
		reservation = Reservation.new(reservation_params)
		reservation.user_id = current_user.id
		reservation.listing_id = params[:listing_id]

		if reservation.save
			flash[:success] = "Successfully made reservation"
			ReservationMailer.new_reservation(reservation.user).deliver
		else
			flash[:error] = reservation.errors.full_messages.join(', ')	
		end	
		
		redirect_to listing_path(params[:listing_id])
	end


  private
  	def reservation_params
   	 	params.require(:reservation).permit(:start_date, :end_date)
  	end

end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
def create_from_omniauth
  auth_hash = request.env["omniauth.auth"]
  authentication = Authentication.find_by_provider_and_uid(auth_hash["provider"], auth_hash["uid"]) ||  Authentication.create_with_omniauth(auth_hash)

  # if: previously already logged in with OAuth
  if authentication.user
    user = authentication.user
    authentication.update_token(auth_hash)
    @next = root_url
    @notice = "Signed in!"
  # else: user logs in with OAuth for the first time
  else
    user = User.create_with_auth_and_hash(authentication, auth_hash)
    # you are expected to have a path that leads to a page for editing user details
    @next = root_url
    @notice = "User created. Please confirm or edit details"
  end

  sign_in(user)
  redirect_to @next, :notice => @notice
end
end

app/controllers/users_controller.rb
class UsersController < Clearance::UsersController
  def show
	  @user = User.find(params[:id])
 
  end

  def edit
    @user = User.find(params[:id])

  end

  def update
		@user = User.find(params[:id])
		if @user.update(user_params)
  	 redirect_to @user
		else
  	 render 'edit'
  	end
	end


  private
	def user_params
 	 	params.require(:user).permit(:email, :password, :avatar)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def show
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_class(level)
    case level
        when :notice then "alert alert-info"
        when :success then "alert alert-success"
        when :error then "alert alert-error"
        when :alert then "alert alert-error"
    	end
	end
end

app/views/braintree/new.html.erb
<h1>Braintree Payment System</h1>
<p>Make your payment with Credit Card for your convenience.</p>

<div class="demo-frame">

  <%= form_for :checkout_form, url: reservation_braintree_checkout_path(@reservation.id), html: { id: "cardForm"} do |form| %>

    <%= form.label :card_number, "Credit Card Number", html: {class: "hosted-fields--label"} %>
    <div id="card-number" class="hosted-field"></div>

    <%= form.label :expiration_date, "Expiration Date", html: {class: "hosted-fields--label"} %>
    <div id="expiration-date" class="hosted-field"></div>

    <%= form.label :cvv, "CVV", html: {class: "hosted-fields--label"} %>
    <div id="cvv" class="hosted-field"></div>

    <%= form.hidden_field "payment_method_nonce" %>

    <div class="button-container">
      <%= form.submit "Purchase", disabled: true, class: "button button--small button--green", id: "submit-payment-btn" %>
    </div>
  <% end %>
</div>


<style type="text/css">
	.hosted-field {
	  height: 50px;
	  box-sizing: border-box;
	  width: 100%;
	  padding: 12px;
	  display: inline-block;
	  box-shadow: none;
	  font-weight: 600;
	  font-size: 14px;
	  border-radius: 6px;
	  border: 1px solid #dddddd;
	  line-height: 20px;
	  background: #fcfcfc;
	  margin-bottom: 12px;
	  background: linear-gradient(to right, white 50%, #fcfcfc 50%);
	  background-size: 200% 100%;
	  background-position: right bottom;
	  transition: all 300ms ease-in-out;
	}

	.hosted-fields--label {
	  font-family: courier, monospace;
	  text-transform: uppercase;
	  font-size: 14px;
	  display: block;
	  margin-bottom: 6px;
	}

	.button-container {
	  display: block;
	  text-align: center;
	}

	.button {
	  cursor: pointer;
	  font-weight: 500;
	  line-height: inherit;
	  position: relative;
	  text-decoration: none;
	  text-align: center;
	  border-style: solid;
	  border-width: 1px;
	  border-radius: 3px;
	  -webkit-appearance: none;
	  -moz-appearance: none;
	  display: inline-block;
	}

	.button--small {
	  padding: 10px 20px;
	  font-size: 0.875rem;
	}

	.button--green {
	  outline: none;
	  background-color: #64d18a;
	  border-color: #64d18a;
	  color: white;
	  transition: all 200ms ease;
	}

	.button--green:hover {
	  background-color: #8bdda8;
	  color: white;
	}

	.braintree-hosted-fields-focused {
	  border: 1px solid #64d18a;
	  border-radius: 1px;
	  background-position: left bottom;
	}

	.braintree-hosted-fields-invalid {
	  border: 1px solid #ed574a;
	}

	.braintree-hosted-fields-valid {
	}

	#cardForm {
	  max-width: 50.75em;
	  margin: 0 auto;
	  padding: 1.875em;
	}
</style>

<script>
$(document).on('turbolinks:load', function(){
	var form = document.querySelector('#cardForm');
	var submit = document.querySelector("#submit-payment-btn");
	var authorization = '<%= @client_token %>';

	braintree.client.create({
	  // Replace this with your own authorization.
	  authorization: authorization
	}, function (clientErr, clientInstance) {
	  if (clientErr) {
	    // Handle error in client creation
	    return;
	  }

	  braintree.hostedFields.create({
	    client: clientInstance,
	    styles: {
	      'input': {
	        'font-size': '14pt'
	      },
	      'input.invalid': {
	        'color': 'red'
	      },
	      'input.valid': {
	        'color': 'green'
	      }
	    },
	    fields: {
	      number: {
	        selector: '#card-number',
	        placeholder: '4111 1111 1111 1111'
	      },
	      cvv: {
	        selector: '#cvv',
	        placeholder: '123'
	      },
	      expirationDate: {
	        selector: '#expiration-date',
	        placeholder: '10/2019'
	      }
	    }
	  }, function (hostedFieldsErr, hostedFieldsInstance) {
	    if (hostedFieldsErr) {
	      // Handle error in Hosted Fields creation
	      return;
	    }

	    submit.removeAttribute('disabled');

	    form.addEventListener('submit', function (event) {
	      event.preventDefault();

	      hostedFieldsInstance.tokenize(function (tokenizeErr, payload) {
	        if (tokenizeErr) {
	          // Handle error in Hosted Fields tokenization
	          return;
	        }

	        // Put `payload.nonce` into the `payment_method_nonce` input, and then
	        // submit the form. Alternatively, you could send the nonce to your server
	        // with AJAX.
	        document.querySelector('input[name="checkout_form[payment_method_nonce]"]').value = payload.nonce;
	        form.submit();
	      });
	    }, false);
	  });
	});
})
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Load the Client component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/client.min.js"></script>

    <!-- Load the Hosted Fields component. -->
    <script src="https://js.braintreegateway.com/web/3.6.3/js/hosted-fields.min.js"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 

    <%= button_to 'Home', root_path, method: :get %>

    <% if signed_in? %>

      Signed in as: <%= current_user.email %>
      <%= button_to 'Sign out', sign_out_path, method: :delete %>
      <%= button_to 'Profile', user_path(current_user.id), method: :get %>

    <% else %>

      <%= link_to 'Sign in', sign_in_path %>

    <% end %>


    <div id="flash">
      <% flash.each do |key, value| %>
        <div class="flash <%= key %>"><%= value %></div>
      <% end %>
    </div>

    <%= yield %>

    
  </body>
</html>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= form_for(@listing) do |f| %>
    <%= f.label :property %>
    <%= f.text_field :property %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :country %>
    <%= f.text_field :country %>
    
    <%= f.label :rooms %>
    <%= f.number_field :rooms %>
    
    <%= f.label :toilets %>
    <%= f.number_field :toilets %>
    
    <%= f.label :price %>
    <%= f.number_field :price %>


	<%= f.label :images %>
	<%= f.file_field :images, multiple: true %>

	<%= f.submit %>
<% end %>

app/views/listings/index.html.erb
<h1>Property Listing</h1>

<%= link_to 'New listing', new_listing_path %> 
<table> 
  <% @listings.each do |listing| %>
    <tr>

      <td><strong>Listing Property:</strong><%= listing.property %></td>
      <td><strong>Owner's Name:</strong><%= listing.name %></td>
      <td><strong>Country:</strong><%= listing.country %></td>
      <td><strong>No. of Rooms:</strong><%= listing.rooms %></td>
      <td><strong>No. of Bathrooms:</strong><%= listing.toilets %></td>
      <td><strong>Price per Night:</strong><%= listing.price %></td>
      
      <td><strong>Property Images:</strong>
        <% listing.images.each do |image| %>
          <%= image_tag(image.url, width: 50) %>
        <% end %>
      </td>

      <td><%= link_to 'Show', listing_path(listing) %></td>
      <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
      <td><%= link_to 'Destroy', listing_path(listing),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/listings/new.html.erb
<h1> Create your Listings! </h1>

<%= form_for(@listing) do |f| %>
    <%= f.label :property %>
    <%= f.text_field :property %>
    
    <%= f.label :name %>
    <%= f.text_field :name %>
    
    <%= f.label :country %>
    <%= f.text_field :country %>
    
    <%= f.label :rooms %>
    <%= f.number_field :rooms %>
    
    <%= f.label :toilets %>
    <%= f.number_field :toilets %>
    
    <%= f.label :price %>
    <%= f.number_field :price %>
    

    <h2>Upload your Property Image</h2>

	
	<%= f.label :images %>
	<%= f.file_field :images, multiple: true%>


	<%= f.submit %>
	


<% end %>

app/views/listings/show.html.erb
<%= link_to 'Edit', edit_listing_path(@listing) %>
<strong>Listing Property:</strong>
<%= @listing.property %>
<br>


<strong>Owner's Name:</strong>
<%= @listing.name %>
<br>



<strong>Country:</strong>
<%= @listing.country %>
<br>



<strong>No. of Rooms:</strong>
<%= @listing.rooms %>
<br>



<strong>No. of Bathrooms:</strong>
<%= @listing.toilets %>
<br>



<strong>Price per Night:</strong>
<%= @listing.price %>
<br>



<strong>Property Images:</strong>
<br>
<% @listing.images.each do |image| %>
  <%= image_tag(image.url) %>
<% end %>
<br>
<br>
<% if @listing.user != current_user %>
	<%= form_with model: Reservation.new, url: listing_reservations_path(@listing) do |f| %>
	  <%= f.date_field :start_date, placeholder: 'Check In Date' %><br>
	  <%= f.date_field :end_date, placeholder: 'Check Out Date' %><br>
	  <%= f.submit %>
	<% end %>
<% end %>
<hr>
<h3>Current Reservations</h3>

<% @listing.reservations.each do |reservation| %>
	<ul>
		<li>Start: <%= reservation.start_date %></li>
		<li>End: <%= reservation.end_date %></li>
		<li>Booked by: <%= reservation.user.email %></li>
		<li>Total Price: <%= reservation.total_price %></li>
		<% if reservation.confirmation == true %>
			
		<% else %>
			<% if reservation.user == current_user %>
				<%= link_to "Make Payment", reservation_braintree_new_path(reservation.id) %>
			<% end %>
		<% end %>
		
	</ul>
<% end %>

app/views/users/_form.html.erb
  
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_area :password%>
  </div>

app/views/users/edit.html.erb
<h1>Edit Profile</h1>

<%= form_for(@user) do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.submit %>
<% end %>


<h1>Upload your photo</h1>

<%= form_with model: @user,local: true do |f|%>
	<%= f.label :avatar %>
	<%= f.file_field :avatar %>
	<%= f.submit %>
<% end %>

app/views/users/index.html.erb
<%= image_tag(@user.image_url(:thumb).to_s) %>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>  

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<p> Hello, Welcome to your Profile </p>

<% if @user.avatar.url %>
 <%= image_tag(@user.avatar.url) %>
<% end %>
<br>
<%= @user.email %>
<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', root_path %>

app/views/welcome/show.html.erb
<h1> Welcome to AirBnB Clone! </h1>
<%= link_to "Sign in with Google", "/auth/google_oauth2" %>


<h2>Listings </h2>
<%= link_to 'All Listings', controller: 'listings' %>
<%= link_to 'New Listings', controller: 'listings' %>


<h2>Search  </h2>
<%= form_tag(search_path, method: :get ) do %>
  Country: <%= text_field_tag :country %><br/>
  Property: <%= text_field_tag :property %><br/>
  Rooms: <%= text_field_tag :rooms %><br/>
  <%= submit_tag 'Search', name: nil %>
<% end %>



<h2>Users</h2>
<% User.all.each do |user| %>
	<ul>
		<li>id: <%= user.id %></li>
		<li>email:  <%= link_to user.email, user_path(user) %></li>
	</ul>

<% end %>